### ISSUE TITLE
ProposiciónLógicaLizbeth

### ISSUE THREAD

**Issue by BautistaLizbeth** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-BautistaLizbeth#1]
[proposiciones.logicas.Lizbeth.docx](https://github.com/user-attachments/files/17549453/proposiciones.logicas.Lizbeth.docx)

**Comment by josealfredo79** [comment]
No se puede descargar

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Calificacion 20
